version: '3'

services:
  dotnet:
    image: dotnet
    container_name: dotnet
    ports:
      - 8080:80
    environment: 
      - ConnectionStrings:MySQLConnection=Server=35.185.190.1;Port=31593;User=root;Password=P@ssw0rd;Database=DOTNET-5
    # depends_on: 
    #   - db

  # db:
  #   image: mariadb:10.6.0
  #   container_name: db
  #   ports: 
  #     - 3306:3306
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=DOTNET-5